=== MarkM-Portfolio/sn.auto/XMLMigration/Config/ForumConfig/forum-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- 5724-S31                                                          -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2006, 2012  All Rights Reserved.              -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with           -->
<!-- IBM Corp.                                                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<!-- 5724-S68                                                          -->
<!-- 5724-L21                                                          -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
 <xs:annotation>
  <xs:documentation>
    Activities - IBM Lotus Social Networking Software. 
    Licensed Materials - Property of IBM.
    (C) Copyright IBM Corp. 2006. All Rights Reserved. 
    US Government Users Restricted Rights - Use, duplication or
    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
  </xs:documentation>
 </xs:annotation>
 <xs:element name='activeContentFilter'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='tags'  minOccurs='0'/>
     <xs:element ref='mimeTypes'/>
   </xs:sequence>
   <xs:attribute name='class' use='optional' type='xs:NMTOKEN'/>
   <xs:attribute name='enabled' use='required' type='xs:boolean'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='discussThis'>
  <xs:complexType>
   <xs:sequence>
     <xs:element name='targetBookmarklet' type='xs:string'/>
   </xs:sequence>
   <xs:attribute name='enabled' use='required' type='xs:boolean'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='any-header-expression'>
  <xs:complexType mixed='true'>
  <xs:attribute name='header' use='required' type='xs:NMTOKEN'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='config'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='webUi' minOccurs='0'/>
     <xs:element ref='eventBroker' minOccurs='1'/>
     <xs:element ref='scheduledTasks' minOccurs='1'/>
     <xs:element ref='deployment' minOccurs='0'/>
     <xs:element ref='objectStore' minOccurs='0'/>
     <xs:element ref='registerMbeans' minOccurs='1'/>
     <xs:element ref='activeContentFilter' minOccurs='0'/>
     <xs:element ref='javalin' minOccurs='0'/>
     <xs:element ref='dojo' minOccurs='0'/>
     <xs:element ref='discussThis' minOccurs='0'/>
   </xs:sequence>
   <xs:attribute name='id' use='required' type='xs:NMTOKEN'/>
   <xs:attribute name='version' use='required' type='xs:NMTOKEN'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='create'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='databaseType'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='error'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='event'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='eventBroker'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='subscriber' minOccurs='1' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name='events'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='event' minOccurs='0' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name='filter'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='property' maxOccurs='unbounded'/>
   </xs:sequence>
  <xs:attribute name='class' use='required' type='xs:NMTOKEN'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='footer'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='header'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='host'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='id'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='images-prefix'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='isClustered'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='javalin'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='javalinCard' minOccurs='0'/>
     <xs:element ref='sametimePresence' minOccurs='0'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name='javalinCard'>
  <xs:complexType>
  <xs:attribute name='enabled' use='required' type='xs:boolean'/>
  <xs:attribute name='url' use='required'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='jmx'>
  <xs:complexType>
  <xs:attribute name='enabled' use='required' type='xs:boolean'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='limit'>
  <xs:complexType mixed='true'>
  <xs:attribute name='mimeFilenameRegex' use='required'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='deployment'>
  <xs:complexType>
   <xs:attribute name='enableCategory' use='required' type='xs:boolean'/>
   <xs:attribute name="enableLotusLive" use="optional" type="xs:boolean" />
   <xs:attribute name='enableNonMemberContributor' use='optional' type='xs:boolean'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='registerMbeans'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='jmx'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name='max-number-attachment-per-post' type='xs:nonNegativeInteger'/>
 <xs:element name="allow-upload" type="xs:boolean"/>
 <xs:element name='mimeType'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='mimeTypes'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='mimeType' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name='notify'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='objectStore'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='store' maxOccurs='unbounded'/>
     <xs:element ref='sizeLimits' minOccurs='0'/>
     <xs:element ref='max-number-attachment-per-post' minOccurs='0'/>
     <xs:element ref="allow-upload"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 
  <!--  -->
  <xs:element name='scheduledTasks'>
   <xs:complexType>
    <xs:sequence>
      <xs:element ref='task' minOccurs='1' maxOccurs="unbounded" />
    </xs:sequence>
   </xs:complexType>
  </xs:element>
  <!-- --> 
 <xs:element name='task'>
	<xs:complexType>
		<xs:sequence>
		<xs:element ref='args'  minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="interval" type="xs:string" use="required" />
		<xs:attribute name="startby" type="xs:string" use="required" />

		<xs:attribute name="type" type="xs:string" use="required" />
		<xs:attribute name="enabled" type="xs:boolean" use="required" />
		<xs:attribute name="targetName" type="xs:string" use="required" />
		<xs:attribute name="mbeanMethodName" type="xs:string" use="required" />
		<xs:attribute name="scope" type="xs:string" use="required" />
		<xs:attribute name="serverName" type="xs:string" use="required" />
		<xs:attribute name="description" type="xs:string" use="required" />
	</xs:complexType>
 </xs:element>

 <xs:element name='args'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='property' minOccurs='0'  maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element> 
 <xs:element name='password'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='authentry'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='property'>
  <xs:complexType mixed='true'>
  <xs:attribute name='name' type='xs:NMTOKEN'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='reject-filter'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='any-header-expression'/>
   </xs:sequence>
  <xs:attribute name='deleteMatches' use='required' type='xs:NMTOKEN'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='sametimePresence'>
  <xs:complexType>
  <xs:attribute name='enabled' use='required' type='xs:boolean'/>
  <xs:attribute name='url' use='required'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='samples'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='sizeLimits'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='limit' minOccurs='0' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name='store'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='id'/>
     <xs:element ref='property' maxOccurs='unbounded'/>
   </xs:sequence>
  <xs:attribute name='class' use='required' type='xs:NMTOKEN'/>
  <xs:attribute name='default' use='required' type='xs:NMTOKEN'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='subscriber'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='events'/>
     <xs:element ref='property' minOccurs='0' maxOccurs='unbounded'/>
   </xs:sequence>
  <xs:attribute name='class' use='required' type='xs:NMTOKEN'/>
  </xs:complexType>
 </xs:element>
 <xs:element name='tag'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='tags'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='tag'  minOccurs='0' maxOccurs='unbounded'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name='size-limit'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element> 
 <xs:element name='tools'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='user'>
  <xs:complexType mixed='true'>
  </xs:complexType>
 </xs:element>
 <xs:element name='webUi'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='header'/>
     <xs:element ref='footer'/>
     <xs:element ref='tools'/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
<xs:element name='dojo'>
<xs:complexType>
<xs:attribute name='url' use='optional' type='xs:string'/>
</xs:complexType>
</xs:element>
</xs:schema>

=== MarkM-Portfolio/sn.auto/XMLMigration/Config/ForumConfig/forum-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Copyright IBM Corp. 2009, 2011  All Rights Reserved.              -->

<!-- 5724-S68                                                          -->
<config version="4" id="forum-config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="forum-config.xsd">

    <!--  Forums Configuration   -->

    <!--
        The Event Broker is used to control the transmission of events to the Homepage
    -->
    <eventBroker>
        <!-- Maintain this XML formatting for the subscriber element so it can be handled by the installer -->
        <!-- This provider sends Audit / News events to the Homepage when data changing events occur -->
        <subscriber class="com.ibm.lconn.forum.internal.service.core.AuditEventDispatcher">
           <events>
              <event>com.ibm.lconn.forum.events.ForumPublishedEvent</event>
           </events>
        </subscriber>
    </eventBroker>

    <scheduledTasks>
      <!-- cluster scoped jobs -->

      <!-- TrashAutoPurgeJob - weekly on Sundays at 2:00AM  0 0 2 ? * SUN  -->
      <task name="TrashAutoPurgeJob" description="Permanently removes Forums Trash"
            interval="0 0 2 ? * SUN" startby=""
            enabled="true" scope="cluster" type="class"
            targetName="com.ibm.lconn.forum.internal.jobs.TrashAutoPurgeJobWS"
            mbeanMethodName="" serverName="unsupported" >
            <!-- trashRetentionInDays: Specify the number of days that deleted content is left in the
                 database as soft deleted. Note: the <trashRetentionInDays> element value must be 1 or
                 greater. If the value is less than 1 the trash will not be purged by this job
                 runTimeInMin: Specify the time (in minutes) the task should run. -->
            <args>
                <property name="trashRetentionInDays">90</property>
                <property name="runTimeInMin">120</property>
            </args>
      </task>
    </scheduledTasks>

    <!-- used to configure deployment enableNonMemberContributor="false" mode 'with categories' or 'no categories' -->
    <deployment enableNonMemberContributor="false" enableCategory="false" />
    
    <!--
        The Object Store is used to store attachments. Multiple object stores can be specified, but
        only one can be marked as "default". The default store is used for all new content. The "id"
        element must be a unique name, it does not need to specify a specific type or be a keyword
        like "filesystem".
    -->
    
    <objectStore>
        <!-- Maintain this XML formatting for the store element so it can be handled by the installer -->
        <store default="true" class="com.ibm.lconn.forum.internal.objectstore.filesystem.FileSystemObjectStore">
            <id>filesystem</id>
            <property name="root.directory">${FORUM_CONTENT_DIR}</property>
        </store>
        <!-- Setting a size limit on content, by mime type or filename, will prevent the content from being accepted and
            stored if the content's size is larger than specified. Use a regular expression to match the desired
            mime type or filename. If none of the expressions match, then there's no size limit on that type of content.
            These settings apply to all content store objects for new data.

            The size limit should be denoted in bytes.
            1024 bytes equals 1 Kb. 1,048,576 bytes equal 1 MB. -->
        <sizeLimits>
            <limit mimeFilenameRegex=".*\.exe">0</limit>
            <limit mimeFilenameRegex=".*\.bat">0</limit>
            <limit mimeFilenameRegex=".*\.sh">0</limit>
            <limit mimeFilenameRegex=".*\.oa">0</limit>
            <limit mimeFilenameRegex=".*">10485760</limit>
        </sizeLimits>
        
        <max-number-attachment-per-post>6</max-number-attachment-per-post>
        <!-- Used to open/close the upload function.  -->
        <allow-upload>true</allow-upload>
    </objectStore>

    <!-- used to be 'management'-->
    <registerMbeans>
        <jmx enabled="true" />
    </registerMbeans>

    <!-- Define content that will be removed from forum data -->
    <activeContentFilter enabled="true">
        <mimeTypes>
            <mimeType>text/html</mimeType>
            <mimeType>application/xhtml+xml</mimeType>
        </mimeTypes>
    </activeContentFilter>

</config>
