=== MarkM-Portfolio/sn.auto/XMLMigration/Config/NotificationConfig/notification-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- 5724-S31                                                          -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2008, 2012  All Rights Reserved.              -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with           -->
<!-- IBM Corp.                                                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name='config'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='properties' minOccurs='0' maxOccurs="1"/>
				<xs:element ref='handlers' />				
				<xs:element ref='channelConfigs' />
				<xs:element ref='defaultEmailPreferences'/>
				<xs:element ref='templates' minOccurs='0' />
			</xs:sequence>
			<xs:attribute name='id' use='required' type='xs:NMTOKEN' />
			<xs:attribute name='buildlevel' type="xs:string" use='required'/>
			<xs:attribute name='version' use='required'
				type='xs:NMTOKEN' />
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="handlers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="handler" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

	<xs:element name="handler">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" />
			<xs:attribute name="name" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="defaultEmailPreferences">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="allowEmailAddressOverride" minOccurs='1' maxOccurs='1' type="xs:boolean" />
				<xs:element name="useLanguageFromCallingComponent" minOccurs='1' maxOccurs='1' type="xs:boolean"/>
				<xs:element name='defaultLanguage' minOccurs='1' maxOccurs='1' type="xs:string"/>
				<xs:element name="sendEmailsForDirectNotifications" minOccurs='1' maxOccurs="1" type="xs:boolean"/>
				<xs:element name="defaultEmailFormat" minOccurs='0' maxOccurs="1">
					<xs:simpleType>
                    	<xs:restriction base="xs:string">
                        	<xs:enumeration value="HTML"/>
                        	<xs:enumeration value="PLAIN"/>
                   		</xs:restriction>
                	</xs:simpleType>
				</xs:element>
				<xs:element name="defaultResponsesFrequency" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
	                    <xs:restriction base="xs:string">
	                        <xs:enumeration value="NONE"/>
	                        <xs:enumeration value="INDIVIDUAL"/>
	                        <xs:enumeration value="DAILY"/>
	                        <xs:enumeration value="WEEKLY"/>
	                    </xs:restriction>
                	</xs:simpleType>
				</xs:element>
				<xs:element name="defaultTagFollowFrequency" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
	                    <xs:restriction base="xs:string">
	                        <xs:enumeration value="NONE"/>
	                        <xs:enumeration value="INDIVIDUAL"/>
	                        <xs:enumeration value="DAILY"/>
	                        <xs:enumeration value="WEEKLY"/>
	                    </xs:restriction>
                	</xs:simpleType>
				</xs:element>
				<xs:element name="defaultMentionsFollowFrequency" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
	                    <xs:restriction base="xs:string">
	                        <xs:enumeration value="NONE"/>
	                        <xs:enumeration value="INDIVIDUAL"/>
	                        <xs:enumeration value="DAILY"/>
	                        <xs:enumeration value="WEEKLY"/>
	                    </xs:restriction>
                	</xs:simpleType>
				</xs:element>
				<xs:element name="defaultTopicsFollowFrequency" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
	                    <xs:restriction base="xs:string">
	                        <xs:enumeration value="NONE"/>
	                        <xs:enumeration value="INDIVIDUAL"/>
	                        <xs:enumeration value="DAILY"/>
	                        <xs:enumeration value="WEEKLY"/>
	                    </xs:restriction>
                	</xs:simpleType>
				</xs:element>
				<xs:element name="replyToEnabled" minOccurs="1" maxOccurs="1" type="xs:boolean"/>
				<xs:element name="digestItemsPerCategory" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
	                    <xs:restriction base="xs:integer">
	                    	<xs:minInclusive value="5"/>
 							<xs:maxInclusive value="25"/>
	                    </xs:restriction>
                	</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	

	<xs:element name="templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="source" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="source">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="imagesURL" type="xs:string" />
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
			<xs:attribute name="defaultFollowFrequency">
				<xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="NONE"/>
                        <xs:enumeration value="INDIVIDUAL"/>
                        <xs:enumeration value="DAILY"/>
                        <xs:enumeration value="WEEKLY"/>
                    </xs:restriction>
                </xs:simpleType>			
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="type">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="channel" maxOccurs="unbounded"
					minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="notificationType">
				<xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="DIRECTED"/>
                        <xs:enumeration value="FOLLOW"/>
                        <xs:enumeration value="BROADCAST"/>
                        <xs:enumeration value="DIGEST"/>
                        <xs:enumeration value="RESPONSE"/>
                        <xs:enumeration value="MODERATION"/>
                    </xs:restriction>
                </xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="channel">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="channelConfigs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="emailChannelConfig" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="emailChannelConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="useJavaMailProvider" minOccurs='0' maxOccurs="1"
					type="xs:boolean" />
				<xs:element name='smtpJNDILookup' minOccurs='0' maxOccurs="1" />
				<xs:element name="maxRecipients" minOccurs='0' maxOccurs="1" type="xs:int"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="smtpJNDILookup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="smtpJNDILookupURL" type="xs:string" />
				<xs:element name="authentry" type="xs:string" />
				<xs:element name="user" type="xs:string" />
				<xs:element name="password" type="xs:string" />
				<xs:element name="javamail" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="javamail">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="property">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string"></xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== MarkM-Portfolio/sn.auto/XMLMigration/Config/NotificationConfig/notification-config (2).xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright IBM Corp. 2008, 2012  All Rights Reserved.              -->

<config id="notification-config" version="4.0" buildlevel="LC4.0_20120605_1157"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="notification-config.xsd" enabled="true">
	<properties>
		<property name="globalSenderEmailAddress">global-admin@example.com</property>
		<!-- If true a link to Connections Mobile service will be included in 
			Notifications (where applicable) -->
		<property name="includeMobileLinksInNotifications">false</property>
		<!-- If true no embedded experience mime parts will be included in notifications -->
		<property name="disableEmbeddedAppsInNotifications">false</property>
	</properties>
	<handlers>
		<handler name="email"
			class="com.ibm.lotus.connections.core.notify.channels.email.EmailNotificationChannelHandler" />
		<handler name="event"
			class="com.ibm.lotus.connections.core.notify.channels.event.EventNotificationChannelHandler" />
		<handler name="clientHandler"
			class="com.ibm.lotus.connections.core.notify.handlers.event.EventNotificationHandler" />
	</handlers>
	<channelConfigs>
		<emailChannelConfig>
			<useJavaMailProvider>true</useJavaMailProvider>
			<!--smtpJNDILookup>
				<smtpJNDILookupURL>dns:[//host[:port]][/domain]</smtpJNDILookupURL>
	            <authentry>smtpAdmin</authentry>
	            <javamail>
	                <property name="mail.debug">false</property>
	                <property name="mail.smtp.connectiontimeout">120000</property>
	                <property name="mail.smtp.timeout">120000</property>
	            	<property name="mail.smtp.port">465</property>
	                <property name="mail.smtp.socketFactory.port">465</property>
	                <property name="mail.smtp.socketFactory.class">javax.net.ssl.SSLSocketFactory</property>
	                <property name="mail.smtp.socketFactory.fallback">false</property>
	            </javamail>
			</smtpJNDILookup-->
			<maxRecipients>50</maxRecipients>
		</emailChannelConfig>
	</channelConfigs>
	
	<!-- Sets default email preferences for users who have not set their own
	     preferences. -->
	<defaultEmailPreferences>
		<!-- If true, users will be able to override the email address that emails
		     to them will be delivered to. -->
		<allowEmailAddressOverride>false</allowEmailAddressOverride>
		<!-- If true, then if the user has not specified a preferred langague for
		     emails to be delivered in then the langauge they last visited the 
		     web UI for the component generating the email will be used. This 
		     is the default behaviour in previous versions. -->
		<useLanguageFromCallingComponent>true</useLanguageFromCallingComponent>
		<!-- If useLanguageFromCallingComponent is false, then if the user has not
		     set their own language preference, this default language will be used. -->
		<defaultLanguage>en</defaultLanguage>
		<!-- The default for whether directed notification (sent from one user to another
		     or by the system should be received by email. These notification are also 
		     aggregated onto the Home Page. -->
		<sendEmailsForDirectNotifications>true</sendEmailsForDirectNotifications>
		<!-- Specifies how email notifications for responses to authored content are
			 sent. Options are INDIVIDUAL (single, immediate emails) DAILY, WEEKLY or NONE. -->
		<defaultResponsesFrequency>INDIVIDUAL</defaultResponsesFrequency>
		<!-- Specifies how email notifications updates about tags a user is following are
			 sent. Options are INDIVIDUAL (single, immediate emails) DAILY, WEEKLY or NONE. -->
		<defaultTagFollowFrequency>WEEKLY</defaultTagFollowFrequency>
		<!-- The default for whether replyTo is enabled. This defines if user
			will have ability to reply to supported notifications to respond
			(e.g. replying to a forum response notification to add a new response -->
		<replyToEnabled>true</replyToEnabled>
		<!-- The default amount of stories to be included in every category
			in the Daily and Weekly Email Digest. Min is 5, Max is 25 -->
		<digestItemsPerCategory>10</digestItemsPerCategory>
	</defaultEmailPreferences>
	
	<templates>
		<!-- Example
			<source name="Activities" enabled="true" defaultFollowFrequency="DAILY">
				<type name="notify"  notificationType="DIRECTED">
					<channel name="email" enabled="true">
						<property name="sender">activities-admin@example.com</property>
						<property name="ftl">notify.ftl</property>
					</channel>
					<channel name="event" enabled="true">
						<property name="eventName">activities.notify</property>
						<property name="transformerClass">sample.ActivityNotifyTransformer</property>
					</channel>
				</type>
			</source>
		-->
		<source name="Activities" enabled="true" defaultFollowFrequency="DAILY">
			<type name="notify" notificationType="DIRECTED">
				<channel name="email" enabled="true">
					<property name="sender">activities-admin@example.com</property>
					<property name="ftl">notifyMail.ftl</property>
				</channel>
				<channel name="event" enabled="true">
					<property name="eventName">activities.notification.notify</property>
					<property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.ActivitiesNotificationEventTransformer</property>
				</channel>
			</type>
			<type name="autocomplete" notificationType="DIRECTED">
				<channel name="email" enabled="true">
					<property name="sender">activities-admin@example.com</property>
					<property name="ftl">autoCompleteActivityMail.ftl</property>
				</channel>
				<channel name="event" enabled="true">
					<property name="eventName">activities.notification.autocomplete</property>
					<property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.ActivitiesNotificationEventTransformer</property>
				</channel>
			</type>
			<type name="create" notificationType="DIRECTED">
				<channel name="email" enabled="true">
					<property name="sender">activities-admin@example.com</property>
					<property name="ftl">createMail.ftl</property>
				</channel>
				<channel name="event" enabled="true">
					<property name="eventName">activities.notification.create</property>
					<property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.ActivitiesNotificationEventTransformer</property>
				</channel>
			</type>
            <type name="add-member" notificationType="DIRECTED">
                <channel name="email" enabled="true">
                    <property name="sender">activities-admin@example.com</property>
                    <property name="ftl">addMemberMail.ftl</property>
                </channel>
                <channel name="event" enabled="true">
                    <property name="eventName">activities.notification.addmember</property>
                    <property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.ActivitiesNotificationEventTransformer</property>
                </channel>
            </type>
            <type name="invite" notificationType="DIRECTED">
                <channel name="email" enabled="true">
                    <property name="sender">activities-admin@example.com</property>
                    <property name="ftl">inviteMemberMail.ftl</property>
                </channel>
                <channel name="event" enabled="true">
                    <property name="eventName">activities.notification.invitemember</property>
                    <property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.ActivitiesNotificationEventTransformer</property>
                </channel>
            </type>
		</source>
		<source name="dogear" enabled="true" defaultFollowFrequency="WEEKLY">
			<type name="notify" notificationType="DIRECTED">
				<channel name="email" enabled="true">
					<property name="sender">dogear-admin@example.com</property>
					<property name="ftl">notifytemplate.ftl</property>
				</channel>	
				<channel name="event" enabled="true">
					<property name="eventName">dogear.notification.notify</property>
					<property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.DogearNotificationEventTransformer</property>
				</channel>			
			</type>
			<type name="brokenurl" notificationType="DIRECTED">
				<channel name="email" enabled="true">
					<property name="sender">dogear-admin@example.com</property>
					<property name="ftl">notifytemplate.ftl</property>
				</channel>
				<channel name="event" enabled="true">
					<property name="eventName">dogear.notification.brokenurl</property>
					<property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.DogearNotificationEventTransformer</property>
				</channel>
			</type>			
            <type name="notifyReplaceURL" notificationType="DIRECTED">
				<channel name="email" enabled="true">
					<property name="sender">dogear-admin@example.com</property>
					<property name="ftl">replaceurltemplate.ftl</property>
				</channel>
				<channel name="event" enabled="true">
					<property name="eventName">dogear.notification.replaceurl</property>
					<property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.DogearNotificationEventTransformer</property>
				</channel>
			</type>			
		</source>
		<source name="Blogs" enabled="true" defaultFollowFrequency="WEEKLY">
			<type name="notify" notificationType="DIRECTED">
				<channel name="email" enabled="true">
					<property name="sender">blogs-admin@example.com</property>
					<property name="ftl">notify.ftl</property>
				</channel>
				<channel name="event" enabled="true">
					<property name="eventName">blogs.notification.notify</property>
					<property name="transformerClass">com.ibm.lotus.connections.core.notify.channels.event.BlogsNotificationEventTransformer</property>
				</channel>
			</type>
			<type name="notify-idea" notificationType="DIRECTED">
