=== MarkM-Portfolio/sn.auto/XMLMigration/Config/DogearConfig/dogear-config-cell.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- 5724-S31                                                          -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2006, 2012  All Rights Reserved.              -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with           -->
<!-- IBM Corp.                                                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ibm.com/dogear-config-cell" targetNamespace="http://www.ibm.com/dogear-config-cell">
  <xsd:element name="personThresholds">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="integerProperty"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="capacity" type="xsd:string"/>
  <xsd:element name="jndi" type="xsd:string"/>
  <xsd:element name="ipRange">
    <xsd:complexType>
      <xsd:attribute name="to" type="xsd:string"/>
      <xsd:attribute name="from" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="urlPattern" type="xsd:string"/>
  <xsd:element name="type">
  	<xsd:complexType>
	    <xsd:sequence>
	    	<xsd:element ref="urlPattern" maxOccurs="unbounded" minOccurs="0"></xsd:element>
	    </xsd:sequence>
	    <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
  	</xsd:complexType>
  </xsd:element>
  <xsd:element name="tag" type="xsd:string"/>
  <xsd:element name="contextParameters">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="stringProperty"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="tags">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element minOccurs="0" maxOccurs="unbounded" ref="tag"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="stringProperty">
    <xsd:complexType mixed="true">
    	<xsd:simpleContent>
    		<xsd:extension base="xsd:string">
     	 		<xsd:attribute name="name" type="xsd:string"/>
     	 	</xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="integerProperty">
    <xsd:complexType mixed="true">
    	<xsd:simpleContent>
    		<xsd:extension base="xsd:integer">
     	 		<xsd:attribute name="name" type="xsd:string"/>
     	 	</xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="longProperty">
    <xsd:complexType mixed="true">
    	<xsd:simpleContent>
    		<xsd:extension base="xsd:long">
     	 		<xsd:attribute name="name" type="xsd:string"/>
     	 	</xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="booleanProperty">
    <xsd:complexType mixed="true">
    	<xsd:simpleContent>
    		<xsd:extension base="xsd:boolean">
     	 		<xsd:attribute name="name" type="xsd:string"/>
     	 	</xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="privateIntranetAllocationTable">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element minOccurs="0" maxOccurs="unbounded" ref="ipRange"/>
		<xsd:element minOccurs="0" maxOccurs="unbounded" ref="urlPattern"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="name" type="xsd:string"/>
  <xsd:element name="activeContentFilter">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="tags"/>
      </xsd:sequence>
      <xsd:attribute name="enabled" type="xsd:boolean"/>
       <xsd:attribute name="enhanced" type="xsd:boolean"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="contentTypes">
  	<xsd:complexType>
  		<xsd:sequence>
  			<xsd:element minOccurs="0" maxOccurs="unbounded" ref="type"/>
  		</xsd:sequence>
  		<xsd:attribute name="enabled" use="required" type="xsd:boolean"/>
  	</xsd:complexType>
  </xsd:element>
 
  <xsd:element name="structuredTags" >
	  <xsd:complexType>
		  <xsd:sequence>
			  <xsd:element minOccurs="0" maxOccurs="unbounded" ref="tag"/>
		  </xsd:sequence>
		  <xsd:attribute name="enabled" use="required" type="xsd:boolean"/>
	  </xsd:complexType>
  </xsd:element>
  <xsd:element name="redirectDogearThis">
	  <xsd:complexType>
		  <xsd:attribute name="enabled" use="required" type="xsd:boolean"/>
		  <xsd:attribute name="destination" use="required" type="xsd:string"/>
	  </xsd:complexType>
  </xsd:element>
  <xsd:element name="cachePublicData">
	  <xsd:complexType>
		  <xsd:attribute name="enabled" use="required" type="xsd:boolean"/>
		  <xsd:attribute name="max-age" use="required" type="xsd:int"/>
	  </xsd:complexType>
  </xsd:element>
  <xsd:element name="cacheFactory">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="cache"/>
      </xsd:sequence>
      <xsd:attribute name="defaultCapacity" type="xsd:string" use="optional"/>
      <xsd:attribute name="class" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="cache">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="name"/>
        <xsd:element minOccurs="0" ref="capacity"/>
        <xsd:element minOccurs="0" ref="jndi"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element> 
  <xsd:element name="linkPurgingTask">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="integerProperty"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="transactionSyncLogConsumerTask">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="integerProperty"/>
        <xsd:element maxOccurs="unbounded" ref="longProperty"/>
        <xsd:element maxOccurs="unbounded" ref="stringProperty"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="favIconService">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="stringProperty"/>
        <xsd:element maxOccurs="unbounded" ref="integerProperty"/>
        <xsd:element maxOccurs="unbounded" ref="booleanProperty"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="brokenURLService">
	<xsd:complexType>
	  <xsd:sequence>
	    <xsd:element maxOccurs="unbounded" ref="booleanProperty"/>
	  </xsd:sequence>
	</xsd:complexType>
  </xsd:element>
  <xsd:element name="serviceBehavior">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="booleanProperty"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="config">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="contextParameters"/>
        <xsd:element ref="favIconService"/>
        <xsd:element ref="brokenURLService"/>
        <xsd:element ref="privateIntranetAllocationTable"/>
        <xsd:element ref="linkThresholds"/>
        <xsd:element ref="tagThresholds"/>
        <xsd:element ref="personThresholds"/>
        <xsd:element ref="contentTypes"/>
        <xsd:element ref="activeContentFilter"/>
		<xsd:element ref="redirectDogearThis"/>
		<xsd:element ref="cachePublicData"/>
        <xsd:element ref="cacheFactory"/>
        <xsd:element ref="linkPurgingTask"/>
        <xsd:element ref="serviceBehavior"/>
        <xsd:element ref="embedStyle"/>
        <xsd:element minOccurs="0" maxOccurs="1" ref="transactionSyncLogConsumerTask" />
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:string" use="required"/>
      <xsd:attribute name="buildlevel" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="linkThresholds">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="integerProperty"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="tagThresholds">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="integerProperty"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="embedStyle">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="stringProperty"/>
      </xsd:sequence>
      <xsd:attribute name="enabled" type="xsd:boolean"/>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== MarkM-Portfolio/sn.auto/XMLMigration/Config/DogearConfig/dogear-config-cell (2).xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Copyright IBM Corp. 2006, 2012  All Rights Reserved.              -->

<config id="dogearcell" buildlevel="20120605_1219" 
	xmlns="http://www.ibm.com/dogear-config-cell" 
	xmlns:tns="http://www.ibm.com/dogear-config-cell" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ibm.com/dogear-config-cell dogear-config-cell.xsd">

	<contextParameters>
 		<stringProperty name="platform">@Platform@</stringProperty>
    </contextParameters>

	<!-- Fav Icon Service  -->
	<favIconService>
		<stringProperty name="favicon.directory">${DOGEAR_FAVICON_DIR}</stringProperty>
		<!-- in days -->
		<integerProperty name="favicon.maxAge">90</integerProperty> 
		<!-- in KB -->
		<integerProperty name="favicon.maxSize">6</integerProperty> 
		<!-- in minutes -->
		<integerProperty name="favicon.start">5</integerProperty> 
		<integerProperty name="favicon.queuesize">100</integerProperty>
	    <booleanProperty name="favicon.ajaxproxy.intranet.enabled">true</booleanProperty>
	</favIconService>
	
	<!-- Broken URL Service  -->
	<brokenURLService>
		<booleanProperty name="brokenURL.notifyAllOwners">true</booleanProperty>
		<booleanProperty name="brokenURL.notifyAdmin">true</booleanProperty>
	</brokenURLService>
		 	 
	  <!--  
	 	Intranet IP Range (inclusive)
	  -->
	 <privateIntranetAllocationTable>
	 	
	 </privateIntranetAllocationTable>
	 	 
	 	 
	 <!--
	 	Dogear Link Thresholds
	  -->
	  <linkThresholds>
	  	<integerProperty name="sinceWhen.popularLinks">30</integerProperty> <!-- in  days -->
	  	<integerProperty name="maxInclude.popularLinks">2000</integerProperty> <!-- number of links -->
	  	<integerProperty name="sinceWhen.inboxLinks">20</integerProperty> <!-- in  days -->
		<integerProperty name="sinceWhen.mostVisitedLinks">30</integerProperty> <!-- in  days -->
		<integerProperty name="minLinkCount.useCountCache">100000</integerProperty> <!-- number of links -->
		<integerProperty name="minURLCount.useCountCache">10000</integerProperty> <!-- number of URLs -->
		<integerProperty name="countInterval.useCountCache">10</integerProperty> <!-- number of count interval -->
	  </linkThresholds>
	  
	  <!--
	 	Dogear Tag Thresholds
	  -->
	  <tagThresholds>
	  	<integerProperty name="sinceWhen.activeTags">30</integerProperty>  <!-- in  days -->
		<integerProperty name="minCount.activeTags">1</integerProperty>  <!--  min frequency -->
	  	<integerProperty name="maxInclude.activeTags">4000</integerProperty> <!-- number of tags -->
	  </tagThresholds>
	  
	   <!--
	 	Dogear Person Thresholds
	   -->
	  <personThresholds>
	  	<integerProperty name="sinceWhen.activePerson">30</integerProperty>  <!-- in  days -->
		<integerProperty name="minCount.activePerson">5</integerProperty>  <!--  min frequency -->
	  	<integerProperty name="maxInclude.activePerson">1500</integerProperty> <!-- number of links -->
	  </personThresholds>
	  
	  <!--
	  	Content Type Definitions
	  -->
	  
	  <contentTypes enabled="false">
	  	<!-- 
			Type Definition
		-->
		<!--
	  	<type name="blogs">
			<urlPattern>http://blogs/*</urlPattern>
		</type>
		-->
	  </contentTypes>
	  
	  <activeContentFilter enabled="true" enhanced="true">
		<tags>
			<!-- tags only used with basic ACF, not with enhanced ACF.
			<tag>iframe</tag>
			<tag>applet</tag>
			<tag>script</tag>
			<tag>object</tag>
			<tag>embed</tag>
			<tag>a</tag>
			-->
		</tags>
	  </activeContentFilter>
	  
	  <redirectDogearThis enabled="true" destination="/bookmarklet/post" />
	  <cachePublicData enabled="true" max-age="120"/>
	  
	 <!--   
	    Dogear Cache Factory
	  	Note: Some config params may be ignored by certain cache implementations. The class 
	  	attribute is always required.  The LruCacheFactory is not clusterable.
	  -->
	  <!--
	  <cacheFactory class="com.ibm.cue.cache.lru.LruCacheFactory" defaultCapacity="10000" >
		<cache>
			<name>dogear.freshness</name>
			<capacity>10000</capacity>
		</cache>
	  </cacheFactory>
	 -->
	 
	  <cacheFactory class="com.ibm.cue.cache.dynacache.DynaCacheFactory" >
		<cache>
			<name>dogear.freshness</name>
			<jndi>services/cache/dogear.freshness</jndi>
		</cache>
	  </cacheFactory>
		  	  
	 <!--  
		The background link purging task
	 -->
	 <linkPurgingTask>
	 	<!-- in minutes -->
	 	<integerProperty name="lpTask.start">15</integerProperty>  
		<!-- in minutes -->
		<integerProperty name="lpTask.interval">60</integerProperty>  
		<!-- in days -->
		<integerProperty name="lpTask.purgeDeleted">30</integerProperty> 
	 </linkPurgingTask>
	 
	 <!-- The configurable behaviors in Bookmarks (aka Dogear) -->
	 <serviceBehavior>
	    <booleanProperty name="bookmark.openInNewWindow">false</booleanProperty>
	 </serviceBehavior>
	   <!--
        The embed snippet CSS white list
      -->
	  <embedStyle enabled="false">
	    <!-- font family white list-->
	    <stringProperty name="font.familyList">Times,Arial,Times New Roman,Verdana,Helvetica,Geneva</stringProperty>
	    <!-- font color white list-->
	    <stringProperty name="font.colorList">red,blue,green,yellow,orange,black,white,gold,snow</stringProperty>
	  </embedStyle>
</config>
