=== MarkM-Portfolio/sn.auto/XMLMigration/Config/CommunitiesPolicy/communities-policy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- 5724-S31                                                          -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2007, 2012  All Rights Reserved.              -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with           -->
<!-- IBM Corp.                                                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<!-- 5724-S68                                                          -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	targetNamespace="http://www.ibm.com/connections/communities/communities-policy/1.0"
	xmlns:tns="http://www.ibm.com/connections/communities/communities-policy/1.0"
	xmlns:xml="http://www.w3.org/XML/1998/namespace">

	<xs:annotation>
		<xs:documentation>
			Tango - IBM Tango Communities Licensed
			Materials - Property of IBM. (C) Copyright IBM Corp. 2006
			All Rights Reserved. US Government Users Restricted Rights -
			Use, duplication or disclosure restricted by GSA ADP
			Schedule Contract with IBM Corp.
		</xs:documentation>
	</xs:annotation>
		
	<xs:attributeGroup name="Common.Attributes">
		<xs:annotation>
			<xs:documentation>Attributes for _every_ element in TangoConfig</xs:documentation>
		</xs:annotation>
		<xs:anyAttribute namespace="##other"/>
	</xs:attributeGroup>
	
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
					<xs:element name="policy" type="tns:policy" minOccurs="1" maxOccurs="1"/>
					<xs:any namespace="##other" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="tns:Common.Attributes"/>
 	        	<xs:attribute name="id" type="xs:string"/>
		</xs:complexType>
	</xs:element>

 
  <xs:complexType name='policy'>
   <xs:sequence>
     <xs:element ref='tns:grant' minOccurs='0' maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType> 

 <xs:element name='grant'>
  <xs:complexType>
   <xs:sequence>
     <xs:element ref='tns:principal' minOccurs='1' maxOccurs="1"/>
     <xs:element ref='tns:permission' minOccurs='1' maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>

 <xs:element name='principal'>
  <xs:complexType>
   <xs:attribute name='class' use='required'/>
   <xs:attribute name='name' use='required'/>
  </xs:complexType>
 </xs:element>

 <xs:element name='permission'>
  <xs:complexType>
   <xs:attribute name='class' use='required'/>
   <xs:attribute name='communityType' use='required'/>
   <xs:attribute name='action' use='required'/>
  </xs:complexType>
 </xs:element>
	
</xs:schema>

=== MarkM-Portfolio/sn.auto/XMLMigration/Config/CommunitiesPolicy/communities-policy3New.xml
<?xml version="1.0" encoding="UTF-8"?>

  <!--		
     ***************************************************************** 
	                                                                  
      Licensed Materials - Property of IBM                            
                                                                      
      5724-S68
	                                                                  
      Copyright IBM Corp. 2001, 2010  All Rights Reserved.            
                                                                      
      US Government Users Restricted Rights - Use, duplication or     
      disclosure restricted by GSA ADP Schedule Contract with         
      IBM Corp.                                                       
                                                                      
     ***************************************************************** 
		--><comm:config xmlns:comm="http://www.ibm.com/connections/communities/communities-policy/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="communities-policy" xsi:schemaLocation="http://www.ibm.com/connections/communities/communities-policy/1.0 communities-policy.xsd">
<comm:policy>
<!-- reader -->
<comm:grant>
      <comm:principal class="com.ibm.tango.auth.principal.Role" name="reader"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="public" action="passive"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="publicInviteOnly" action="passive"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityInvitePermission" communityType="public" action="passive"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityInvitePermission" communityType="publicInviteOnly" action="passive"/>
    </comm:grant>
<!-- community-creator -->
<comm:grant>
      <comm:principal class="com.ibm.tango.auth.principal.Role" name="community-creator"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="public" action="create"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="publicInviteOnly" action="create"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="private" action="create"/>
    </comm:grant>
<!-- person -->
<!-- personNonmember -->
<comm:grant>
      <comm:principal class="com.ibm.tango.auth.principal.Role" name="personNonmember"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="public" action="add.self"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="publicInviteOnly" action="requestToJoin"/>
    </comm:grant>
<!-- Community member -->
<comm:grant>
<comm:principal class="com.ibm.tango.auth.principal.Role" name="member"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="private" action="passive"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="public" action="active"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="publicInviteOnly" action="active"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="private" action="active"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="public" action="conditional.create"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="publicInviteOnly" action="conditional.create"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="private" action="conditional.create"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityBroadcastPermission" communityType="public" action="mail"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityBroadcastPermission" communityType="publicInviteOnly" action="mail"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityBroadcastPermission" communityType="private" action="mail"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityInvitePermission" communityType="public" action="create"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityInvitePermission" communityType="private" action="passive"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="public" action="add.self"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="publicInviteOnly" action="requestToJoin"/>
</comm:grant>
<!-- Community explicit-member -->
<comm:grant>
<comm:principal class="com.ibm.tango.auth.principal.Role" name="explicit-member"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="private" action="passive"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="public" action="active"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="publicInviteOnly" action="active"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityAccessPermission" communityType="private" action="active"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="public" action="remove.self"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="publicInviteOnly" action="remove.self"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="private" action="remove.self"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="public" action="conditional.create"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="publicInviteOnly" action="conditional.create"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="private" action="conditional.create"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityBroadcastPermission" communityType="public" action="mail"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityBroadcastPermission" communityType="publicInviteOnly" action="mail"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityBroadcastPermission" communityType="private" action="mail"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityInvitePermission" communityType="public" action="create"/>
<comm:permission class="com.ibm.tango.auth.permission.CommunityInvitePermission" communityType="private" action="passive"/>
</comm:grant>
<!-- Reference creator -->
<comm:grant>
      <comm:principal class="com.ibm.tango.auth.principal.Role" name="reference.creator"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="public" action="conditional.update"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="publicInviteOnly" action="conditional.update"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="private" action="conditional.update"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="public" action="conditional.delete"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="publicInviteOnly" action="conditional.delete"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="private" action="conditional.delete"/>
    </comm:grant>
<!-- Community owner -->
<comm:grant>
      <comm:principal class="com.ibm.tango.auth.principal.Role" name="owner"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="public" action="edit"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="publicInviteOnly" action="edit"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="private" action="edit"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="public" action="delete"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="publicInviteOnly" action="delete"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityManagementPermission" communityType="private" action="delete"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="public" action="add.others, remove.others, define.roles"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="publicInviteOnly" action="add.others, remove.others, define.roles"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityMembershipPermission" communityType="private" action="add.others, remove.others, define.roles"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="public" action="conditional.update"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="publicInviteOnly" action="conditional.update"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="private" action="conditional.update"/>
      <comm:permission class="com.ibm.tango.auth.permission.CommunityReferencePermission" communityType="public" action="conditional.delete"/>
