=== MarkM-Portfolio/sn.auto/XMLMigration/Config/DogearConfig/ContentReviewConfig/contentreview-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- 5724-S31                                                          -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2008, 2012  All Rights Reserved.              -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with           -->
<!-- IBM Corp.                                                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<!-- 5724_S68                                                          -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="contentreview-config-i18n.xsd"/>
  <xs:element name="config">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element maxOccurs="unbounded" minOccurs="0" ref="flagCategories">
	      </xs:element>
	      <xs:element maxOccurs="1" minOccurs="0" ref="commModerationConfiguration">
	      </xs:element>
	      <xs:element maxOccurs="unbounded" minOccurs="0" ref="serviceConfiguration">
		  </xs:element>
	    </xs:sequence>
		<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
	  	<xs:attribute name="version" type="xs:NMTOKEN" use="required"/>
	  </xs:complexType>
  </xs:element>
  
  <xs:element name="flagCategories">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="flagCategory"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="flagCategory">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element maxOccurs="unbounded" minOccurs="0" name="id" type="xs:string"/>
	      <xs:element maxOccurs="unbounded" minOccurs="0" name="description">
			  	<xs:complexType mixed="true">
			  		<xs:attribute ref="xml:lang"/>
			  	</xs:complexType>
	      </xs:element>
	      <xs:element maxOccurs="unbounded" minOccurs="0" ref="reviewer">
	      </xs:element>
	    </xs:sequence>
	      <xs:attribute name="id" type="xs:string"/>
	  </xs:complexType>
  </xs:element>
  
	<xs:element name="email" type="xs:string">
	</xs:element>

	<xs:element name="userid" type="xs:string">
	</xs:element>

  <xs:element name="reviewer">
     <xs:complexType>
      <xs:sequence>
       <xs:element ref="email" minOccurs="0" maxOccurs="1"/>
       <xs:element ref="userid" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
        <xs:attribute name="email" type="xs:string"/>
        <xs:attribute name="userid" type="xs:string"/>
     </xs:complexType>
   </xs:element>
          
    <xs:element name="moderator">
	   <xs:complexType>
        <xs:attribute name="email" type="xs:string" use="required"/>
       </xs:complexType>
    </xs:element>
 
    <xs:element name="serviceConfiguration">
      <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="service">
        </xs:element>
      </xs:sequence>
      </xs:complexType>
    </xs:element>
       
    <xs:element name="service">
      <xs:complexType>
      <xs:sequence>
      	<xs:element maxOccurs="1" minOccurs="1" ref="contentApproval">
	 	</xs:element>
	 	<xs:element maxOccurs="1" minOccurs="1" ref="contentFlagging">
	 	</xs:element>
	 	<xs:element maxOccurs="unbounded" minOccurs="0" name="moderator">
        </xs:element>
      </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:element> 
        
    <!-- Default = TRUE -->
    <xs:element name="contentFlagging">
      <xs:complexType>
      <xs:sequence>
        <xs:element ref="ownerModerate" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="automaticQuarantine" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="issueCategorization" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
        <xs:attribute name="enabled" type="xs:boolean" default="true"/>
      </xs:complexType>
    </xs:element>
        
<!-- Default = FALSE -->
    <xs:element name="contentApproval">
    <xs:complexType>
    <xs:sequence>
        <xs:element ref="ownerModerate" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>        
       <xs:attribute name="enabled" type="xs:boolean" default="false"/>
    </xs:complexType>
    </xs:element>
    
  
  <!-- Default = FALSE, threshold = 10 -->
  <xs:element name="automaticQuarantine">
  <xs:complexType>
  	<xs:attribute name="enabled" type="xs:boolean" default="false"/>
  	<xs:attribute name="threshold" type="xs:positiveInteger" default="10"/>
  </xs:complexType>
  </xs:element>

  <!-- Default = TRUE -->
  <xs:element name="issueCategorization">
  <xs:complexType>
  <xs:sequence>
    <xs:element ref="flagCategory" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>    
  	<xs:attribute name="enabled" type="xs:boolean" default="false"/>
  </xs:complexType>
  </xs:element>

  <!-- Default = FALSE -->
  <xs:element name="ownerModerate">
  <xs:complexType>
    <xs:attribute name="enabled" type="xs:boolean" default="false"/>
  </xs:complexType>
  </xs:element> 

  <xs:element name="commModerationConfiguration">
  <xs:complexType>
  	<xs:sequence>
  		<xs:element maxOccurs="1" minOccurs="1" ref="preModeration">
  		</xs:element>
  		<xs:element maxOccurs="1" minOccurs="1" ref="postModeration">
  		</xs:element>
  	</xs:sequence>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="preModeration">
  <xs:complexType>
  	<xs:sequence>
  		<xs:element maxOccurs="1" minOccurs="1" ref="forceForAllCommunities">
  		</xs:element>
  		<xs:element maxOccurs="1" minOccurs="1" ref="enabledByCreation">
  		</xs:element>
  	</xs:sequence>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="postModeration">
  <xs:complexType>
  	<xs:sequence>
  		<xs:element maxOccurs="1" minOccurs="1" ref="forceForAllCommunities">
  		</xs:element>
  		<xs:element maxOccurs="1" minOccurs="1" ref="enabledByCreation">
  		</xs:element>
  	</xs:sequence>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="forceForAllCommunities">
  <xs:complexType>
	<xs:attribute name="enabled" type="xs:boolean" default="true"></xs:attribute>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="enabledByCreation">
  <xs:complexType>
  	<xs:attribute name="enabled" type="xs:boolean" default="true"></xs:attribute>
  </xs:complexType>
  </xs:element>
</xs:schema>

=== MarkM-Portfolio/sn.auto/XMLMigration/Config/ContentReviewConfig/contentreview-config (2).xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright IBM Corp. 2009, 2012  All Rights Reserved.              -->

<!-- 5724_S68                                                          -->
<config id="contentreview-config" version="3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contentreview-config.xsd">
<!-- 
Flag categories are used when issueCategorization is enabled for a specific service. 
When turned on, end users who flag content as inappropriate must select a category for 
the content. Two default categories are provided. You can edit those categories or extend 
the list by adding new categories in this section. For more information, see the topic 
"Managing content moderation and flagged content" in the Administration section of the 
product documentation.
 -->
  <flagCategories>
	  <flagCategory>
	    <id>001</id>
	    <description xml:lang="en">Legal issue</description>
	    <description xml:lang="ar">مشكلة قانونية</description>
	    <description xml:lang="ca">Assumpte legal</description>
	    <description xml:lang="cs">Právní informace</description>
	    <description xml:lang="da">Juridisk afdeling</description>
	    <description xml:lang="de">Rechtlich</description>
	    <description xml:lang="el">Νομικές πληροφορίες</description>
	    <description xml:lang="es">Legal</description>
	    <description xml:lang="fi">Käyttöehdot</description>
	    <description xml:lang="fr">Légal</description>
	    <description xml:lang="hu">Jogi információk</description>
	    <description xml:lang="it">Note legali</description>
	    <description xml:lang="iw">מידע משפטי</description>
	    <description xml:lang="ja">法的問題</description>
	    <description xml:lang="kk">Заңды мәселе</description>
	    <description xml:lang="ko">법적 문제</description>
	    <description xml:lang="nl">Kennisgevingen</description>
	    <description xml:lang="no">Juridisk</description>
	    <description xml:lang="pl">Informacje prawne</description>
	    <description xml:lang="pt-BR">Problema jurídico</description>
	    <description xml:lang="pt">Legal</description>
	    <description xml:lang="ru">Юридическая информация</description>
	    <description xml:lang="sl">Zakonska izdaja</description>
	    <description xml:lang="sv">Juridiska problem</description>
	    <description xml:lang="th">ประเด็นด้านกฎหมาย</description>
	    <description xml:lang="tr">Yasal</description>
	    <description xml:lang="zh-TW">法律條款</description>
	    <description xml:lang="zh">法律条款</description>
	  </flagCategory>
	  <flagCategory>
	    <id>002</id>
	    <description xml:lang="en">Human Resources issue</description>
	    <description xml:lang="ar">مشكلة تتعلق بالموارد البشرية</description>
	    <description xml:lang="ca">Assumpte de recursos humans</description>
	    <description xml:lang="cs">Lidské zdroje</description>
	    <description xml:lang="da">Personaleafdeling</description>
	    <description xml:lang="de">Personalwesen</description>
	    <description xml:lang="el">Ανθρώπινοι πόροι</description>
	    <description xml:lang="es">Recursos humanos</description>
	    <description xml:lang="fi">Henkilöstöhallinto</description>
	    <description xml:lang="fr">Ressources humaines</description>
	    <description xml:lang="hu">Emberi erőforrások</description>
	    <description xml:lang="it">Risorse umane</description>
	    <description xml:lang="iw">משאבי אנוש</description>
	    <description xml:lang="ja">人事の問題</description>
	    <description xml:lang="kk">Еңбек ресурстары мәселесі</description>
	    <description xml:lang="ko">인적 자원 문제</description>
	    <description xml:lang="nl">Human resources</description>
	    <description xml:lang="no">Personale</description>
	    <description xml:lang="pl">Kadry</description>
	    <description xml:lang="pt-BR">Problema de Recursos Humanos</description>
	    <description xml:lang="pt">Recursos Humanos</description>
	    <description xml:lang="ru">Управление персоналом</description>
	    <description xml:lang="sl">Izdaja za kadrovsko službo</description>
	    <description xml:lang="sv">Personalproblem</description>
	    <description xml:lang="th">ประเด็นด้านทรัพยากรบุคคล</description>
	    <description xml:lang="tr">İnsan Kaynakları</description>
	    <description xml:lang="zh-TW">人力資源</description>
	    <description xml:lang="zh">人力资源</description>
	  </flagCategory>
  </flagCategories>   
  
   
<!-- content moderation settings -->

<commModerationConfiguration>
	<preModeration>
		<forceForAllCommunities enabled="false" />
		<enabledByCreation enabled="false" />
	</preModeration>
	<postModeration>
		<forceForAllCommunities enabled="false" />
		<enabledByCreation enabled="false" />
	</postModeration>
</commModerationConfiguration>

<!--
See the topic "Managing content moderation" in the Connection Information Center for details. 
 
<reviewer>, these are the reviewers that will receive email notification when categorization is 
turned on for the flag inappropriate content feature. Reviewers must be assigned the J2EE moderator role. 
<flagCategory id="xxxx">, id is the <id> element defined in the <flagCategory> above
When categorization is turned on, flagging content will require users to select a category
and e-mail notification will be sent to the reviewers assigned to the selected category
-->            
  <serviceConfiguration>
	<service id="blogs">
		<contentApproval enabled="false">
		    <ownerModerate enabled="false"/>
		</contentApproval>
		<contentFlagging enabled="false">
		    <ownerModerate enabled="false"/>
			<issueCategorization enabled="false">
                <flagCategory id="001">
				    <reviewer email="reviewer1@example.com"/>
	                <reviewer email="reviewer2@example.com"/>
                </flagCategory>
                <flagCategory id="002">
                    <reviewer email="reviewer1@example.com"/>
                    <reviewer email="reviewer3@example.com"/>
                </flagCategory>
			</issueCategorization>
		</contentFlagging>
		<!-- 
		Moderators specified here will receive e-mail notification about content 
		needing moderation for this service. 
		-->		
		<moderator email="moderator1@example.com"/>
		<moderator email="moderator2@example.com"/>          
	</service>

	<service id="files">
		<contentApproval enabled="false">
		    <ownerModerate enabled="false"/>
        </contentApproval>
		<contentFlagging enabled="false">
		    <ownerModerate enabled="false"/>
		</contentFlagging>
        <!-- 
        Moderators specified here will receive e-mail notification about content 
        needing moderation for this service. 
        -->		
		<moderator email="moderator3@example.com"/>
		<moderator email="moderator4@example.com"/>                
	</service>
	
	<service id="forums">
		<contentApproval enabled="false">
            <ownerModerate enabled="false"/>
        </contentApproval>
		<contentFlagging enabled="false">
			<ownerModerate enabled="false"/>
			<automaticQuarantine enabled="false" threshold="10" />
			<issueCategorization enabled="false">
                <flagCategory id="001">
                    <reviewer email="reviewer1@example.com"/>
                    <reviewer email="reviewer2@example.com"/>
                </flagCategory>
                <flagCategory id="002">
                    <reviewer email="reviewer2@example.com"/>
                    <reviewer email="reviewer3@example.com"/>
                </flagCategory>
            </issueCategorization>
		</contentFlagging>
        <!-- 
        Moderators specified here will receive e-mail notification about content 
        needing moderation for this service. 
        -->
		<moderator email="moderator5@example.com"/>
		<moderator email="moderator6@example.com"/>                
	</service>
  </serviceConfiguration>
  		
</config>
